### ISSUE TITLE
关于 IPv6 的获取

### ISSUE THREAD

**Issue by kotoyuuko** [BoffinZhang/USTB_Network_AutoManager#1]
校园网 IPv6 在连通的情况下可以直接从 [http://cippv6.ustb.edu.cn/get_ip.php](http://cippv6.ustb.edu.cn/get_ip.php) 获取到，直接使用即可。获取网卡的 IP 在不同设备运行结果可能不一致。

另外你的校园网账号和密码暴露在代码里了，建议即使修改。

**Comment by BoffinZhang** [comment]
已做相应修改，感谢您的提醒~





---原始邮件---
发件人: "kotoyuuko"<notifications@github.com&gt;
发送时间: 2019年11月18日(星期一) 晚上7:12
收件人: "BoffinZhang/USTB_Network_AutoManager"<USTB_Network_AutoManager@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [BoffinZhang/USTB_Network_AutoManager] 关于 IPv6 的获取 (#1)



校园网 IPv6 在连通的情况下可以直接从 http://cippv6.ustb.edu.cn/get_ip.php 获取到，直接使用即可。获取网卡的 IP 在不同设备运行结果可能不一致。
 
另外你的校园网账号和密码暴露在代码里了，建议即使修改。
